/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai1` | `/bai1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai2` | `/bai2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai3` | `/bai3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai4` | `/bai4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bai1` | `/bai1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bai2` | `/bai2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bai3` | `/bai3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bai4` | `/bai4`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bai1${`?${string}` | `#${string}` | ''}` | `/bai1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bai2${`?${string}` | `#${string}` | ''}` | `/bai2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bai3${`?${string}` | `#${string}` | ''}` | `/bai3${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bai4${`?${string}` | `#${string}` | ''}` | `/bai4${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai1` | `/bai1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai2` | `/bai2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai3` | `/bai3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bai4` | `/bai4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
